### PR TITLE
Add .npmignore file and use dist/js/hopscotch.min.js as main in package.json

### PR DESCRIPTION
**Pull request by kate2753**
Hopefully last change towards resolving #150. 

This PR adds `.npmignore` file which will exclude all files and folders that are needed for development of hopscotch only. `npm install` of hopscotch will pull down these files and folders:

```console
  - node_modules
    - hopscotch
      - dist/
      - src/
      - CHANGELOG.md
      - CONTRIBUTING.md
      - LICENSE
      - README.md
      - package.json
```

`dist` folder contains all files necessary for using hopscotch (compiled js, css and images). I've also kept `src` folder in case people are customizing look and feel and need `*.less` files.

This PR also updates `main` to be the minified javascript distribution of hopscotch.

### CODE REVIEW

**Comment by zimmi88** [comment]
Looks reasonable to me. Just wondering if we should also include the Gruntfile, in case NPM users want to customize and rebuild Hopscotch in their product?

**Comment by kate2753** [comment]
Good point. I'll remove grunt file from `.npmignore`

**Comment by kate2753** [comment]
Updated. Here's updated list of files and folders that re included:

```console
dist/
src/
CHANGELOG.md
CONTRIBUTING.md
Gruntfile.js
LICENSE
README.md
package.json
```

**Comment by zimmi88** [comment]
Looks good to me!

**Pull request merged**
