### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by zimmi88** [comment]
Hi @kkirsche,

Thanks for the info! Looks reasonable to me, based off of the linked PR. Given this change, can we also update `Gruntfile.js` to remove `bower.json` from the `bump` task?

Thanks!

**Comment by kkirsche** [comment]
@zimmi88 pushed that change for you

**Comment by zimmi88** [comment]
Great, thanks @kkirsche! Assuming Travis CI returns ok, I'll pull this in by EOD tomorrow if there are no objections.

**Comment by kkirsche** [comment]
Sounds good :+1: thanks for your time

**Pull request merged**
